### ISSUE TITLE
Feature request: Crafting materials enhacements

### ISSUE THREAD

**Issue by AurySystem** [LakMoore/InfiniTiC#11]
Right now crafting materials are nice, but they could use some enhancements for adding extra wood or gem material.

- we could use custom material values for blocks and such
- planks and string should get oredict whitelist entry fields
- the option choose what item gets picked for the Materials and You page on the material
- the option to disable head, handle, and/or extra for a material

**Comment by LakMoore** [comment]
I don't completely understand what you are suggesting here.  Can you provide an example of how this might be used?

**Comment by AurySystem** [comment]
Well, I'm going to try to explain it better.

"we could use custom material values for blocks and such" - This is mostly for wood, logs have a crafting material value of four while planks have a value of one. The pack maker may also want to have gems use the block when crafting tool parts, gems could have nine in a block or four hence the reason for it being customizable.

"planks and string should get oredict whitelist entry fields" - For wood, with the goal of making it one hundred percent clear to the pack creator what to define planks for wood as. Probably not necessary right now, in the future it might be needed to add planks as an extra type of block to make.

"the option choose what item gets picked for the Materials and You page on the material" - This is for if the pack creator wants the logs display on the side of the page, with the meltibilty and tool previews. 

"the option to disable head, handle, and/or extra for a material" This is for custom bow string/fletching only materials, but it could be used for a binding, head, or handle only material. Say the pack creator has a material like hemp, manastring, or some kind of leaf thing and they don't want people making tools with it but only bow/arrow parts with it.

I hope I explained what I meant and how these might be used by people in a way so you can understand.

**Comment by LakMoore** [comment]
We need to be careful when dealing with the number of items that make the block.  Because you can both melt and cast both items and blocks then it is important that melting and casting values remain constant across both items and blocks.  This gets one level more complex if you want to configure the number of items that make up a block.

I don't really understand your planks/wood/oredict paragraph.  I have only considered this mod for manipulating metals, gems and (more recently) string and leaves.

The item that appears as the "representative item" in Materials and You is the first ingot in the whitelist.  If that does not exist but Gems have been provided then the first Gem is used.  If that does not exist then, in more recent game versions, Tinkers chooses to use the Shard.  This could be configurable in a future version of Infini-TiC.

 Any configurable part can be disabled in Infini-TiC by setting all the relevant stats for that part to zero.

**Comment by LakMoore** [comment]
I don't think there is anything more to be done here.  Thanks for the feedback.
